version: "2"
linters:
  default: standard
  enable:
    - gocritic
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - exitAfterDefer
        - rangeValCopy
